name: Run Playwright Script

on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright requests
          python -m playwright install --with-deps

      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Run script
        run: xvfb-run -a python ply.py

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: video
          path: video.mp4
